# Generated by Django 3.1 on 2022-07-25 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tlApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='userPost',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Post by'),
        ),
    ]
